name: Automated wokflow

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - '*.md'
      - '.sonarcloud.properties'
      - 'data/**'
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.md'
      - '.sonarcloud.properties'
      - 'data/**'
      - 'docs/**'

env:
  REGISTRY: ghcr.io


jobs:
  pullrequest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install requirement
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: python test_app.py >> $GITHUB_STEP_SUMMARY

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: "${{ env.REGISTRY }}/wivik/devops-solutions-map:${{ github.sha }}"
          file: Containerfile
          context: .
