name: Clean old packages

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'devops-solutions-map'
          package-type: 'container'
          min-versions-to-keep: 4

